[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.10"
name = "dgcv"
version = "0.6.0"
description = "Differential Geometry with Complex Variables"
authors = [{ name = "David Sykes", email = "david@realandimaginary.com" }]
license = "Apache-2.0"
license-files = ["LICENSE", "NOTICE"]
dependencies = []
readme = "README.md"

[project.optional-dependencies]
sympy = ["sympy>=1.9"]
ipython = ["ipython>=7.0"]
recommended = ["sympy>=1.9", "ipython>=7.0"]
testing = ["pytest>=8", "pytest-cov>=5"]

[tool.setuptools]
package-dir = { "" = "src" }
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]

[tool.ruff]
line-length = 88
extend-exclude = ["_build", "buck-out", "build", "dist", "tutorials", "*.ipynb"]

[tool.ruff.lint]
select = ["F", "E", "W", "I"]
ignore = ["E501", "Q", "W291"] # global ignores

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]
"tests/**/*.py" = ["F401"]

[tool.black]
line-length = 88
skip-string-normalization = false
target-version = ["py39", "py310", "py311", "py312", "py313"]
