import pytest  # type: ignore

from dgcv.algebras import algebra_class
from dgcv.algebras.algebras_secondary import createAlgebra
from dgcv.core.arrays.arrays import array_dgcv, frozen_matrix_dgcv
from dgcv.secondary_library import defloat


def test_Levi_decomposition(clean_vmf):
    shape = (16, 1)
    sd = array_dgcv(
        {
            128: array_dgcv({0: 2}, shape=shape),
            8: array_dgcv({0: -2}, shape=shape),
            192: array_dgcv({2: -1}, shape=shape),
            12: array_dgcv({2: 1}, shape=shape),
            208: array_dgcv({4: -2}, shape=shape),
            13: array_dgcv({4: 2}, shape=shape),
            65: array_dgcv({0: -1}, shape=shape),
            20: array_dgcv({0: 1}, shape=shape),
            81: array_dgcv({4: 1}, shape=shape),
            21: array_dgcv({4: -1}, shape=shape),
            113: array_dgcv({1: 1}, shape=shape),
            23: array_dgcv({1: -1}, shape=shape),
            129: array_dgcv({1: 1}, shape=shape),
            24: array_dgcv({1: -1}, shape=shape),
            145: array_dgcv({1: 1}, shape=shape),
            25: array_dgcv({1: -1}, shape=shape),
            161: array_dgcv({2: 1}, shape=shape),
            26: array_dgcv({2: -1}, shape=shape),
            177: array_dgcv({10: 1}, shape=shape),
            27: array_dgcv({10: -1}, shape=shape),
            209: array_dgcv({7: 1, 8: 1}, shape=shape),
            29: array_dgcv({7: -1, 8: -1}, shape=shape),
            225: array_dgcv({6: -1}, shape=shape),
            30: array_dgcv({6: 1}, shape=shape),
            241: array_dgcv({14: -1}, shape=shape),
            31: array_dgcv({14: 1}, shape=shape),
            50: array_dgcv({0: -1}, shape=shape),
            35: array_dgcv({0: 1}, shape=shape),
            114: array_dgcv({2: 1}, shape=shape),
            39: array_dgcv({2: -1}, shape=shape),
            130: array_dgcv({2: 1}, shape=shape),
            40: array_dgcv({2: -1}, shape=shape),
            146: array_dgcv({2: -1}, shape=shape),
            41: array_dgcv({2: 1}, shape=shape),
            194: array_dgcv({6: -1}, shape=shape),
            44: array_dgcv({6: 1}, shape=shape),
            210: array_dgcv({10: 2}, shape=shape),
            45: array_dgcv({10: -2}, shape=shape),
            99: array_dgcv({2: 1}, shape=shape),
            54: array_dgcv({2: -1}, shape=shape),
            115: array_dgcv({3: -1}, shape=shape),
            55: array_dgcv({3: 1}, shape=shape),
            131: array_dgcv({3: 1}, shape=shape),
            56: array_dgcv({3: -1}, shape=shape),
            147: array_dgcv({3: 1}, shape=shape),
            57: array_dgcv({3: -1}, shape=shape),
            163: array_dgcv({4: -1}, shape=shape),
            58: array_dgcv({4: 1}, shape=shape),
            179: array_dgcv({5: -1}, shape=shape),
            59: array_dgcv({5: 1}, shape=shape),
            195: array_dgcv({7: 1 / 2, 8: -1 / 2}, shape=shape),
            60: array_dgcv({7: -1 / 2, 8: 1 / 2}, shape=shape),
            227: array_dgcv({10: -1}, shape=shape),
            62: array_dgcv({10: 1}, shape=shape),
            243: array_dgcv({11: 1}, shape=shape),
            63: array_dgcv({11: -1}, shape=shape),
            116: array_dgcv({4: -1}, shape=shape),
            71: array_dgcv({4: 1}, shape=shape),
            132: array_dgcv({4: 1}, shape=shape),
            72: array_dgcv({4: -1}, shape=shape),
            148: array_dgcv({4: -1}, shape=shape),
            73: array_dgcv({4: 1}, shape=shape),
            196: array_dgcv({10: 1}, shape=shape),
            76: array_dgcv({10: -1}, shape=shape),
            212: array_dgcv({5: 2}, shape=shape),
            77: array_dgcv({5: -2}, shape=shape),
            117: array_dgcv({5: -2}, shape=shape),
            87: array_dgcv({5: 2}, shape=shape),
            149: array_dgcv({5: -2}, shape=shape),
            89: array_dgcv({5: 2}, shape=shape),
            197: array_dgcv({11: 1}, shape=shape),
            92: array_dgcv({11: -1}, shape=shape),
            118: array_dgcv({6: 2}, shape=shape),
            103: array_dgcv({6: -2}, shape=shape),
            150: array_dgcv({6: -2}, shape=shape),
            105: array_dgcv({6: 2}, shape=shape),
            214: array_dgcv({14: -2}, shape=shape),
            109: array_dgcv({14: 2}, shape=shape),
            183: array_dgcv({11: 1}, shape=shape),
            123: array_dgcv({11: -1}, shape=shape),
            199: array_dgcv({12: -1}, shape=shape),
            124: array_dgcv({12: 1}, shape=shape),
            215: array_dgcv({13: 1}, shape=shape),
            125: array_dgcv({13: -1}, shape=shape),
            231: array_dgcv({14: -1}, shape=shape),
            126: array_dgcv({14: 1}, shape=shape),
            184: array_dgcv({11: 1}, shape=shape),
            139: array_dgcv({11: -1}, shape=shape),
            200: array_dgcv({12: 1}, shape=shape),
            140: array_dgcv({12: -1}, shape=shape),
            216: array_dgcv({13: 1}, shape=shape),
            141: array_dgcv({13: -1}, shape=shape),
            232: array_dgcv({14: 1}, shape=shape),
            142: array_dgcv({14: -1}, shape=shape),
            248: array_dgcv({15: 2}, shape=shape),
            143: array_dgcv({15: -2}, shape=shape),
            169: array_dgcv({10: 2}, shape=shape),
            154: array_dgcv({10: -2}, shape=shape),
            185: array_dgcv({11: 3}, shape=shape),
            155: array_dgcv({11: -3}, shape=shape),
            201: array_dgcv({12: 1}, shape=shape),
            156: array_dgcv({12: -1}, shape=shape),
            217: array_dgcv({13: 1}, shape=shape),
            157: array_dgcv({13: -1}, shape=shape),
            233: array_dgcv({14: 3}, shape=shape),
            158: array_dgcv({14: -3}, shape=shape),
            249: array_dgcv({15: 4}, shape=shape),
            159: array_dgcv({15: -4}, shape=shape),
            202: array_dgcv({14: 1}, shape=shape),
            172: array_dgcv({14: -1}, shape=shape),
            218: array_dgcv({11: 2}, shape=shape),
            173: array_dgcv({11: -2}, shape=shape),
            203: array_dgcv({15: -1}, shape=shape),
            188: array_dgcv({15: 1}, shape=shape),
            237: array_dgcv({15: 2}, shape=shape),
            222: array_dgcv({15: -2}, shape=shape),
        },
        shape=(16, 16),
        null_return=frozen_matrix_dgcv({}, shape=shape),
    )
    sd = defloat(sd)
    alg = createAlgebra(sd, "alg", return_created_object=True)
    assert alg.is_Lie_algebra()
    assert alg.dimension == 16
    ss, nilpotent = alg.Levi_decomposition()
    assert ss.is_semisimple
    assert ss.dimension == 6
    assert [len(level) for level in nilpotent.derived_series()] == [10, 9, 0]
    assert [len(level) for level in nilpotent.lower_central_series()] == [10, 9]
    assert ss.is_Lie_algebra(verbose=True)
    assert len(algebra_class(ss.structureData).compute_simple_subalgebras()) == 2
