name: Update dgcv Version Include

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bump-version:
    name: Bump dgcv version include
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: true

      - name: Generate dgcv_version.json include
        run: |
          VERSION="${GITHUB_REF##*/}"
          mkdir -p includes
          echo "{ \"version\": \"${VERSION}\" }" > includes/dgcv_version.json

      - name: Copy version JSON to server via scp
        env:
          HOST: ${{ secrets.RAIHOME }}
          USER: ${{ secrets.MEATRAI }}
          PORT: ${{ secrets.RAISSH }}
          DEPLOY_KEY: ${{ secrets.DGCV_TO_RAI_KEY }}
        run: |
          echo "${DEPLOY_KEY}" > deploy_key.pem
          chmod 600 deploy_key.pem
          scp -i deploy_key.pem -o StrictHostKeyChecking=no -P "${PORT:-22}" \
              includes/dgcv_version.json \
              "${USER}@${HOST}:/home/${USER}/realandimaginary.com/includes/"
          # Clean up
          rm deploy_key.pem
