name: Update dgcv Version Include

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bump-version:
    name: Bump dgcv version include
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: true

      - name: Copy setup.cfg to website via SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.RAIHOME }}
          username: ${{ secrets.MEATRAI }}
          key: ${{ secrets.DGCV_TO_RAI_KEY }}
          port: ${{ secrets.RAISSH }}
          source: "setup.cfg"
          target: "/home/${{ secrets.MEATRAI }}/realandimaginary.com/includes/"
