name: Update dgcv Version Include

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bump-version:
    name: Bump dgcv version include
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: true

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DGCV_TO_RAI_KEY }}

      - name: Copy setup.cfg via scp
        run: |
          scp -o StrictHostKeyChecking=no -P "${{ secrets.RAISSH }}" \
              setup.cfg \
              ${{ secrets.MEATRAI }}@${{ secrets.RAIHOME }}:/home/${{ secrets.MEATRAI }}/realandimaginary.com/includes/
