name: Update dgcv Version Include

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  bump-version:
    name: Bump dgcv version include
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: true

      - name: Copy setup.cfg and README.md via scp
        run: |
          cat << 'EOF' > deploy_key.pem
          ${{ secrets.DGCV_TO_RAI_KEY }}
          EOF
          chmod 600 deploy_key.pem
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no -P "${{ secrets.RAISSH }}" \
              "${{ secrets.MEATRAI }}@${{ secrets.RAIHOME }}" \
              "mkdir -p ~/realandimaginary.com/includes/dgcv"
          VERSION=$(grep -E '^version\s*=' setup.cfg | head -1 | sed -E 's/version\s*=\s*//')
          mkdir -p includes/dgcv
          echo -n "${VERSION}" > includes/dgcv/dgcv_version.txt
          # Generate release date based on current runner date
          RELD_FMT=$(date '+%B %-d, %Y')
          echo -n "$RELD_FMT" > includes/dgcv/latest-rel-date.txt
          scp -i deploy_key.pem -o StrictHostKeyChecking=no -P "${{ secrets.RAISSH }}" \
              setup.cfg README.md includes/dgcv/dgcv_version.txt includes/dgcv/latest-rel-date.txt \
              "${{ secrets.MEATRAI }}@${{ secrets.RAIHOME }}:/home/${{ secrets.MEATRAI }}/realandimaginary.com/includes/dgcv/"
          rm deploy_key.pem
