name: Update dgcv Version Include

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  bump-version:
    name: Bump dgcv version include
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: true

      - name: Generate dgcv_version.json include
        run: |
          VERSION="${GITHUB_REF##*/}"
          mkdir -p includes
          echo "{ \"version\": \"${VERSION}\" }" > includes/dgcv_version.json

      - name: Upload version include to website via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.WEBSITE_HOST }}
          username: ${{ secrets.WEBSITE_USER }}
          key: ${{ secrets.DGCV_TO_RAI_KEY }}
          port: ${{ secrets.WEBSITE_SSH_PORT }}
          source: "includes/dgcv_version.json"
          target: "/home/${{ secrets.WEBSITE_USER }}/realandimaginary.com/includes/"
